/* controllers/distributorController.js */
'use strict';

const Distributor = require('../models/Distributor');
const Expense = require('../models/Expense');
const Order = require('../models/Order'); // Used for B2B Purchase Orders tracking
const AppError = require('../utils/AppError');
const { withTransaction } = require('../utils/dbUtils');

exports.getAllDistributors = async (request, reply) => {
    const distributors = await Distributor.find({ isActive: true }).lean();
    return { success: true, data: distributors };
};

exports.createDistributor = async (request, reply) => {
    const { name, contactPerson, phone, email, serviceablePincodes } = request.body;
    
    const existing = await Distributor.findOne({ name });
    if (existing) {
        throw new AppError('Distributor with this name already exists', 400);
    }

    const newDistributor = new Distributor({
        name,
        contactPerson,
        phone,
        email,
        serviceablePincodes: serviceablePincodes || []
    });

    await newDistributor.save();
    return { success: true, message: 'Distributor created successfully', data: newDistributor };
};

exports.logPayment = async (request, reply) => {
    const { amount, paymentMode, referenceNote } = request.body;
    const distributorId = request.params.id;

    if (!amount || amount <= 0) {
        throw new AppError('Valid payment amount is required', 400);
    }

    const updatedDistributor = await withTransaction(async (session) => {
        const distributor = await Distributor.findById(distributorId).session(session);
        if (!distributor) throw new AppError('Distributor not found', 404);

        if (distributor.totalPendingAmount < amount) {
            throw new AppError(`Cannot overpay. Maximum pending balance is Rs ${distributor.totalPendingAmount}`, 400);
        }

        distributor.totalPendingAmount -= amount;
        distributor.totalPaidAmount += amount;
        
        distributor.paymentHistory.push({
            amountPaid: amount,
            paymentDate: new Date(),
            paymentMode: paymentMode || 'Bank Transfer',
            referenceNote: referenceNote || 'Cleared via Admin Portal'
        });

        await distributor.save({ session });

        // Log this in the global expense ledger for HQ reconciliation
        const expense = new Expense({
            description: `Supplier Payment: ${distributor.name}`,
            amount: amount,
            category: 'Cost of Goods Sold (COGS)',
            paymentMethod: paymentMode || 'Bank Transfer',
            loggedBy: request.user ? request.user.username : 'System',
            storeId: request.user && request.user.tenantId ? request.user.tenantId : null
        });
        await expense.save({ session });

        return distributor;
    });

    return { success: true, message: 'Payment logged to ledger', data: updatedDistributor };
};

// ==========================================
// --- NEW: PHASE 3 DISTRIBUTOR B2B PORTAL ---
// ==========================================

exports.getDistributorPOs = async (request, reply) => {
    // Authenticates the distributor and fetches only B2B orders assigned to them
    const distributorId = request.user && request.user.distributorId ? request.user.distributorId : request.params.id;
    
    if (!distributorId) {
        throw new AppError('Distributor ID context missing', 403);
    }

    // Pulling drafted and active POs generated by local shops
    const purchaseOrders = await Order.find({
        "items.distributorId": distributorId,
        orderType: 'B2B_RESTOCK'
    }).sort({ createdAt: -1 }).lean();

    return { 
        success: true, 
        message: 'B2B Purchase Orders retrieved', 
        count: purchaseOrders.length,
        data: purchaseOrders 
    };
};

exports.updatePurchaseOrderStatus = async (request, reply) => {
    const { status, trackingDetails } = request.body;
    const orderId = request.params.orderId;
    const distributorId = request.user && request.user.distributorId ? request.user.distributorId : request.body.distributorId;

    const validStatuses = ['Accepted', 'Processing', 'Dispatched', 'Delivered'];
    if (!validStatuses.includes(status)) {
        throw new AppError('Invalid B2B fulfillment status', 400);
    }

    const order = await Order.findOneAndUpdate(
        { _id: orderId, "items.distributorId": distributorId },
        { 
            $set: { 
                fulfillmentStatus: status,
                trackingLink: trackingDetails || undefined
            } 
        },
        { new: true }
    );

    if (!order) {
        throw new AppError('Purchase Order not found or unauthorized access', 404);
    }

    return { 
        success: true, 
        message: `B2B Order marked as ${status}`, 
        data: order 
    };
};
